[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "atompaint"
authors = [
  {name = "Kale Kundert", email = "kale@thekunderts.net"},
]
readme = 'README.rst'
dynamic = ["version", "description"]
requires-python = "~=3.10"
classifiers = [
  'Programming Language :: Python :: 3',
]
dependencies = [
  'docopt',
  'escnn',
  'lightning',
  'more_itertools',
  'nestedtext',
  'numba',
  'numpy',
  'overlap',
  'pandas',
  'pandera',
  'pdbecif',
  'pymixbox',
  'scipy',
  'torch',
  'tqdm',
]

[project.optional-dependencies]
test = [
  'pytest',
  'pytest_tmp_files',
  'parametrize_from_file',
  'hypothesis',
]
doc = [
  'sphinx',
  'sphinx_rtd_theme',
  'autoclasstoc',
]

[project.urls]
'Documentation' = 'https://atompaint.readthedocs.io/en/latest/'
'Version Control' = 'https://github.com/kalekundert/atompaint'
'Bug Tracker' = 'https://github.com/kalekundert/atompaint/issues'
'Continuous Integration' = 'https://github.com/kalekundert/atompaint/actions'
'Test Coverage' = 'https://coveralls.io/github/kalekundert/atompaint'

[project.scripts]
ap_choose_origins = "atompaint.transform_pred.datasets.cli:main"
ap_transform_pred = "atompaint.transform_pred.training:main"

[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-glob='*.rst'"
doctest_optionflags = 'NORMALIZE_WHITESPACE'

[tool.coverage.run]
branch = true
parallel = true
source = ['atompaint']

[tool.coverage.report]
exclude_lines = [
    "^\\s*raise AssertionError\\b",
    "^\\s*raise NotImplementedError\\b",
]

[tool.pccc]
header_length = 72
types = ["chore", "docs", "feat", "fix", "perf", "refactor", "style", "test"]
ignore_generated_commits = true
generated_commits = ['^Merge']

[tool.semantic_release]
branch = 'release'
version_variable = 'atompaint/__init__.py:__version__'
build_command = 'python -m pip install flit && flit build'
major_on_zero = false
